### ISSUE TITLE
How can I run the cli tool I am creating without installing it?

### ISSUE THREAD

**Issue by ltpitt** [yankeexe/cookiecutter-python-cli#1]
Thanks for this awesome cookiecutter, I am loving it!

I wanted to ask if it is possible to run the code without installing it every time, it would speed up the coding process a lot.

Have a nice day.

**Comment by yankeexe** [comment]
Hey @ltpitt, did you[ follow these steps](https://github.com/yankeexe/cookiecutter-python-cli#project-setup)?

Once you run `make install` the CLI you are trying to build will be available in **editable** mode, meaning, any changes you make to the CLI will be detected automatically (kind of like Hot Reloading), and you will be able to use it instantly. 

## Possible steps for a solution
- Follow the [steps here](https://github.com/yankeexe/cookiecutter-python-cli#project-setup)
- Make sure you are inside of venv: `which python` should show the path to your virtualenv directory.
- Similarly, make sure your CLI command is in the virtual environment path: `which <cli-name>` or `command -v <cli-name>`
- If the above does not work,
  - `deactivate` current virtual environment
  - delete `venv` directory 
  - create new virtual env
  - activate it 
  - and run `pip install -e .`

Hope this helps :slightly_smiling_face:

**Comment by ltpitt** [comment]
Hi @yankeexe !

Thanks for your quick and clear help...
The only issue I have is that I am a Windows user so the make install does not work for me...
But I will check the Makefile so maybe the commands in it will work also in Windows.

Thanks again :)

**Comment by ltpitt** [comment]
It worked perfectly.

Deeply thank you for this lovely project and for your kind help!

**Comment by yankeexe** [comment]
@ltpitt glad I could help :slightly_smiling_face:
